SELECT 
	COUNT(CPF_CNPJ) AS TOTAL_BASE,
	SUM( 
	CASE
		WHEN TELEFONE IS NULL THEN 1
		ELSE 0
	END) AS TELEFONE_NULL,
	SUM( 
	CASE
		WHEN EMAIL IS NULL THEN 1 
		ELSE 0
	END) AS EMAIL_NULL,
	SUM( 
	CASE
		WHEN TELEFONE AND EMAIL IS NULL THEN 1
		ELSE 0
	END) AS EMAIL_TELEFONE_NULL
FROM TABELA A;
